# Generated by Django 2.0.6 on 2018-07-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('firebase_token', models.TextField(default=None, null=True)),
                ('detail', models.TextField()),
            ],
        ),
    ]
