# Generated by Django 2.0.6 on 2018-07-26 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sendnoti', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
